version: '0.1'
services:
  iris:
    build: ./image-iris
    environment:
      - TZ=CST-8
      - NAME=iris
      # - ISC_DATA_DIRECTORY=/dur/irisdata
    restart: always
    hostname: datafabric
    container_name: iris-showcase
    ports:
      - 1972:1972
      - 52773:52773
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 4096M
        reservations:
          cpus: '1.00'
          memory: 1024M
    # volumes:
    #   - ./irisdata:/dur/irisdata