version: '0.1'
services:
  iris:
    image: intersystemsdc/irishealth-ml-community:latest
    environment:
      IRIS_USERNAME: superuser
      IRIS_PASSWORD: SYS
    restart: always
    hostname: iris
    ports:
      - 1972:1972
      - 52773:52773