version: '0.1'
services:
  iris:
    build: ./image-iris
    environment:
      IRIS_USERNAME: superuser
      IRIS_PASSWORD: SYS
      # - ISC_DATA_DIRECTORY=/dur/irisdata
    restart: always
    hostname: datafabric
    container_name: iris-showcase
    ports:
      - 1972:1972
      - 52773:52773
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    # volumes:
    #   - ./irisdata:/dur/irisdata
  jupyter:
    build: ./image-jupyter
    environment:
      IRIS_HOSTNAME: datafabric
    restart: always
    hostname: jupyter
    container_name: jupyter
    ports:
      - 8888:8888